name: chatwork
version: 0.1.1.0
synopsis: The ChatWork API in Haskell
description: See README at <https://github.com/matsubara0507/chatwork#readme>
maintainer: MATSUBARA Nobutada
author: MATSUBARA Nobutada
copyright: 2017 MATSUBARA Nobutada
license: MIT
github: matsubara0507/chatwork
category: Web

ghc-options: -Wall

dependencies:
  - base >=4.7 && <5
  - aeson >=1.0.2.1 && <1.3
  - aeson-casing >=0.1.0.5 && <0.2
  - bytestring >=0.10.8.1 && <0.11
  - connection >=0.2.7 && <0.3
  - data-default-class >=0.1.2.0 && <0.2
  - http-api-data >=0.3.5 && <0.3.8
  - http-client >=0.5.5.0 && <0.6
  - http-client-tls >=0.3.3.1 && <0.4
  - http-types >=0.9.1 && <0.10
  - req >=0.3.0 && <0.4
  - text >=1.2.2.1 && <1.3

library:
  source-dirs: src
  exposed-modules:
    - ChatWork
    - ChatWork.Client
    - ChatWork.Endpoints
    - ChatWork.Endpoints.Me
    - ChatWork.Endpoints.My
    - ChatWork.Endpoints.Contacts
    - ChatWork.Endpoints.Rooms
    - ChatWork.Endpoints.IncomingRequests
    - ChatWork.MonadHttpIO
    - ChatWork.Types
    - ChatWork.Types.Base
    - ChatWork.Types.Error
    - ChatWork.Types.Me
    - ChatWork.Types.My
    - ChatWork.Types.Contacts
    - ChatWork.Types.Rooms
    - ChatWork.Types.IncomingRequests
    - ChatWork.Utils
  other-modules:
    - ChatWork.Internal

executables:
  sample-exe:
    source-dirs: sample
    main: Main.hs
    dependencies:
      - chatwork

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - servant-server >=0.9.1.1 && <0.12
      - warp >=3.2.11 && <3.3
      - hspec >=2.4.1 && <2.5
