resolver: lts-8.21

packages:
- '.'
- location:
    git: https://github.com/mrkkrp/req.git
    commit: 030d75ac3df2e80db15aa5a481b65ddaa41dd8f6
  extra-dep: true
extra-deps:
- 'req-0.3.0'

flags: {}

extra-package-dbs: []
