resolver: nightly-2017-07-31

packages:
- '.'
- location:
    git: https://github.com/matsubara0507/http-media.git
    commit: 9fb7378bfd186c6f650b8aa9dc66730c063531c0
  extra-dep: true
extra-deps:
- http-media-0.7.1
- servant-0.11
- servant-server-0.11

flags: {}

extra-package-dbs: []
